apiVersion: v1
kind: Service
metadata:
  name: stock-trading-server
spec:
  selector:
    app: stock-trading-server
  ports:
  - name: grpc
    port: 6565
    targetPort: 6565
  - name: health
    port: 8081
    targetPort: 8081
