server:
  port: \

spring:
  application:
    name: stock-trading-server

grpc:
  server:
    port: \
    enable-reflection: \

logging:
  level:
    root: \
    com.javatechie: \
    io.grpc: \

management:
  endpoints:
    web:
      exposure:
        include: \
  endpoint:
    health:
      probes:
        enabled: true
      show-details: \
